name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'card-game-server/**'  # Trigger only on changes in the card-game-server folder

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build the project
        working-directory: ./card-game-server  # Navigate to server folder
        run: |
          # Replace with your server compile/build command
          ./gradlew build 

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t card-game-tomcat:${{ github.sha }} -f ./card-game-server/Dockerfile ./card-game-server

      - name: Push Docker Image to Docker Hub
        run: |
          docker push devjasper0906/card-game-tomcat:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Pull the latest Docker image
            docker pull devjasper0906/card-game-tomcat:${{ github.sha }}
            
            # Stop and remove the current container if it's running
            docker stop my-container || true
            docker rm my-container || true
            
            # Run the new container
            docker run -d --name my-container -p 8081:8080 devjasper0906/card-game-tomcat:${{ github.sha }}
